import type { Service } from "@/lib/types";

export const facial: Service[] = [
    {
        slug: "express-signature-facial",
        categoryId: "facial",
        title: "Express Signature Facial",
        subtitle:
            "A refined 45-minute facial for an instant glow — cleanse, exfoliate, and hydrate for a fresh, polished look.",
        duration: "45 minutes",
        price: "",
        benefits: ["Quick glow boost", "Smoother texture", "Hydration + brightness"],
        whoFor: ["Busy schedules", "Dullness", "Pre-event refresh"],
        image: "",
    },
    {
        slug: "microneedling-new-client",
        categoryId: "facial",
        title: "Microneedling – New Client",
        subtitle:
            "A first-time microneedling appointment focused on a safe, personalized plan for visible improvement over time.",
        duration: "45 minutes",
        price: "",
        benefits: ["Custom plan", "Skin assessment", "Best protocol selection"],
        whoFor: ["New microneedling clients", "Texture", "Fine lines", "Scars"],
        image: "",
    },
    {
        slug: "acne-clarifying-facial",
        categoryId: "facial",
        title: "Acne Clarifying Facial",
        subtitle:
            "Designed for breakout-prone skin. Deep cleansing, gentle exfoliation, and targeted care to calm congestion.",
        duration: "90 minutes",
        price: "$140",
        benefits: ["Decongests pores", "Helps reduce breakouts", "Calms inflammation"],
        whoFor: ["Acne-prone skin", "Clogged pores", "Oily skin"],
        image: "",
    },
    {
        slug: "back-facial",
        categoryId: "facial",
        title: "Back Facial",
        subtitle:
            "A professional treatment for the back that cleanses, exfoliates, and nourishes the skin for a clearer look.",
        duration: "90 minutes",
        price: "$150",
        benefits: ["Deep cleanse for back", "Smoother skin", "Helps with congestion"],
        whoFor: ["Back breakouts", "Rough texture", "Congestion"],
        image: "",
    },
    {
        slug: "basic-facial",
        categoryId: "facial",
        title: "Basic Facial",
        subtitle:
            "A simple, classic facial to cleanse, refresh, and deeply hydrate the skin — perfect for routine maintenance.",
        duration: "60 minutes",
        price: "$100",
        benefits: ["Cleansing + hydration", "Skin balance", "Healthy glow"],
        whoFor: ["All skin types", "Monthly maintenance", "First-time clients"],
        image: "",
    },
    {
        slug: "biorepeel",
        categoryId: "facial",
        title: "BioRePeel",
        subtitle:
            "An innovative Italian chemical peel suitable for all seasons. Helps renew tone, texture, and radiance.",
        duration: "60 minutes",
        price: "$155",
        benefits: ["Brighter tone", "Smoother texture", "Refined pores"],
        whoFor: ["Dullness", "Uneven tone", "Texture"],
        image: "",
    },
    {
        slug: "biorepeel-package-3-session",
        categoryId: "facial",
        title: "BioRePeel Package (3 Sessions)",
        subtitle:
            "A 3-session plan for stronger, more consistent results with progressive improvement in texture and glow.",
        duration: "60 minutes",
        price: "$375",
        benefits: ["Progressive results", "Improved glow", "Smoother texture over time"],
        whoFor: ["Best results seekers", "Texture", "Tone", "Fine lines"],
        image: "",
    },
    {
        slug: "c202-facial",
        categoryId: "facial",
        title: "C202 Facial",
        subtitle:
            "Perfect for dull, tired, or dehydrated skin — targets early signs of aging for a brighter, smoother look.",
        duration: "90 minutes",
        price: "$140",
        benefits: ["Hydration boost", "Brightening", "Smoother texture"],
        whoFor: ["Dehydration", "Dullness", "Early aging signs"],
        image: "",
    },
    {
        slug: "circadia-enzyme-therapy",
        categoryId: "facial",
        title: "Circadia Enzyme Therapy",
        subtitle:
            "A professional enzyme treatment to refine texture, brighten, and support a clearer, more even complexion.",
        duration: "75 minutes",
        price: "$140",
        benefits: ["Gentle resurfacing", "Glow", "Improved clarity"],
        whoFor: ["Sensitive resurfacing", "Dullness", "Texture"],
        image: "",
    },
    {
        slug: "consultation",
        categoryId: "facial",
        title: "Consultation",
        subtitle:
            "A personalized session to understand your skin and choose the most suitable treatments and routine.",
        duration: "15 minutes",
        price: "$30",
        benefits: ["Personalized plan", "Treatment selection", "Clear next steps"],
        whoFor: ["New clients", "Unsure what to choose", "Planning a series"],
        image: "",
    },
    {
        slug: "customized-facial",
        categoryId: "facial",
        title: "Customized Facial",
        subtitle:
            "A tailored facial built around your skin’s needs — every step is customized for visible comfort and results.",
        duration: "75 minutes",
        price: "$135",
        benefits: ["Fully customized", "Balanced skin", "Glow + hydration"],
        whoFor: ["All skin types", "First-time clients", "Ongoing maintenance"],
        image: "",
    },
    {
        slug: "dermaplaning",
        categoryId: "facial",
        title: "Dermaplaning",
        subtitle:
            "A gentle treatment using a sterile surgical scalpel to remove dead skin cells and peach fuzz for a smoother finish.",
        duration: "60 minutes",
        price: "$130",
        benefits: ["Smoother makeup application", "Brighter look", "Soft texture"],
        whoFor: ["Dullness", "Rough texture", "Peach fuzz"],
        image: "",
    },
    {
        slug: "hydro-glow-facial",
        categoryId: "facial",
        title: "Hydro Glow Facial",
        subtitle:
            "A gentle hydro-infusion facial that cleanses, refreshes, and deeply hydrates for a luminous, plump finish.",
        duration: "75 minutes",
        price: "$140",
        benefits: ["Deep hydration", "Glow", "Fresh, clean finish"],
        whoFor: ["Dehydrated skin", "Dullness", "Events"],
        image: "",
    },
    {
        slug: "luxe-lift-anti-aging-facial",
        categoryId: "facial",
        title: "Luxe Lift Powerful Anti-Aging Facial",
        subtitle:
            "A luxurious treatment by Circadia that smooths, lifts, and rejuvenates the skin for a more refined appearance.",
        duration: "90 minutes",
        price: "$155",
        benefits: ["Smoother look", "Lifted feel", "Brighter tone"],
        whoFor: ["Mature skin", "Loss of firmness", "Fine lines"],
        image: "",
    },
    {
        slug: "md-peel",
        categoryId: "facial",
        title: "MD Peel",
        subtitle:
            "Medical peels designed to target a variety of skin concerns with a focused, professional approach.",
        duration: "60 minutes",
        price: "$130",
        benefits: ["Refined texture", "Brighter tone", "More even complexion"],
        whoFor: ["Texture", "Tone", "Congestion", "Fine lines"],
        image: "",
    },
    {
        slug: "microchanneling",
        categoryId: "facial",
        title: "Microchanneling",
        subtitle:
            "A minimally invasive treatment that creates micro-channels to support skin renewal and improve texture and tone.",
        duration: "60 minutes",
        price: "$185",
        benefits: ["Smoother texture", "Improved tone", "Refined pores"],
        whoFor: ["Texture", "Fine lines", "Uneven tone"],
        image: "",
    },
    {
        slug: "microcurrent",
        categoryId: "facial",
        title: "Microcurrent",
        subtitle:
            "A non-invasive facial treatment using low-level electrical currents to support facial contour and glow.",
        duration: "60 minutes",
        price: "$160",
        benefits: ["Lifted look", "Sculpted feel", "Glow boost"],
        whoFor: ["Loss of firmness", "Dullness", "Special events"],
        image: "",
    },
    {
        slug: "microneedling",
        categoryId: "facial",
        title: "Microneedling",
        subtitle:
            "A skin treatment that uses tiny needles to create micro-channels and support renewal for smoother, clearer skin.",
        duration: "60 minutes",
        price: "$220",
        benefits: ["Improved texture", "Helps fine lines", "Supports scar improvement"],
        whoFor: ["Fine lines", "Acne scarring", "Texture"],
        image: "",
    },
    {
        slug: "microneedling-with-exosomes",
        categoryId: "facial",
        title: "Microneedling with Exosomes",
        subtitle:
            "Microneedling + exosomes to support repair, reduce fine lines, improve scars and pigmentation for a more even look.",
        duration: "60 minutes",
        price: "$250",
        benefits: ["Enhanced recovery support", "Brighter tone", "Smoother texture"],
        whoFor: ["Texture", "Scars", "Pigmentation", "Fine lines"],
        image: "",
    },
    {
        slug: "prx-t33-peel",
        categoryId: "facial",
        title: "PRX-T 33 Peel",
        subtitle:
            "A next-level peel option to refine texture and stimulate renewal for a brighter, smoother complexion.",
        duration: "60 minutes",
        price: "$155",
        benefits: ["Brighter tone", "Refined texture", "Fresh glow"],
        whoFor: ["Dullness", "Texture", "Uneven tone"],
        image: "",
    },
    {
        slug: "prx-t33-peel-package-3-session",
        categoryId: "facial",
        title: "PRX-T 33 Peel Package (3 Sessions)",
        subtitle:
            "A 3-session series designed for progressive improvement and longer-lasting results.",
        duration: "60 minutes",
        price: "$375",
        benefits: ["Progressive improvement", "Better tone + texture", "Series results"],
        whoFor: ["Best results seekers", "Texture", "Tone"],
        image: "",
    },
];
